name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.x' # Specify the Node.js version to use
            registry-url: "https://registry.npmjs.org/"
            always-auth: true
            cache: 'yarn' # Cache yarn dependencies

        - name: Install dependencies
          run: yarn install

        - name: Run build
          run: yarn build

        - name: Publish to npm
          run: cd dist/ && yarn publish --access public
          env:
            NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
